export const psychicTools = [
  { label: 'Clairvoyance', value: 'clairvoyance', icon: '' },
  { label: 'Tarot', value: 'tarot', icon: '' },
  { label: 'Palm Reading', value: 'palm-reading', icon: '' },
  { label: 'Coffee Cup Reading', value: 'coffee-cup-reading', icon: '' },
  { label: 'Dream Interpretation', value: 'dream-interpretation', icon: '' },
];

export const psychicTopics = [
  { label: 'Love & Relationship', value: 'love-relationship', icon: '' },
  { label: 'Family & Friends', value: 'family-friends', icon: '' },
  { label: 'Soulmate & Twin Flames', value: 'soulmate-twin-flames', icon: '' },
  { label: 'Career & Success', value: 'career-success', icon: '' },
  { label: 'Cheating & Breakups', value: 'cheating-breakups', icon: '' },
  { label: 'Karma & Past Life', value: 'karma-past-life', icon: '' },
  { label: 'Pet Psychics', value: 'pet-psychics', icon: '' },
];

export const astrologers = [
  {
    name: 'Sara Smith',
    description: 'Expert In Love Life Relationships soulmate Twin',
    imageUrl:
      'https://api-private.atlassian.com/users/224461c5abc74d5c61834d76c15ac2b1/avatar',
    ratings: 4,
    mailRate: 4.99,
    chatRate: 0.99,
    onlineStatus: 'online',
  },
  {
    name: 'John Doe',
    description: 'Master of Emotional Harmony and Friendship Guru',
    imageUrl: 'https://picsum.photos/id/1/200/300',
    ratings: 4.5,
    mailRate: 4.75,
    chatRate: 1.25,
    onlineStatus: 'offline',
  },
  {
    name: 'Emily Johnson',
    description: 'Psychic Adviser for Love and Career Paths',
    imageUrl: 'https://picsum.photos/id/2/200/300',
    ratings: 4.8,
    mailRate: 4.95,
    chatRate: 0.85,
    onlineStatus: 'busy',
  },
  {
    name: 'Alex Williams',
    description: 'Dream Interpreter and Relationship Whisperer',
    imageUrl: 'https://picsum.photos/id/3/200/300',
    ratings: 4.2,
    mailRate: 4.85,
    chatRate: 1.05,
    onlineStatus: 'away',
  },
  {
    name: 'Olivia Brown',
    description: 'Astrology Enthusiast and Life Coach',
    imageUrl: 'https://picsum.photos/id/4/200/300',
    ratings: 4.6,
    mailRate: 4.9,
    chatRate: 0.95,
    onlineStatus: 'online',
  },
  {
    name: 'Ethan Miller',
    description: 'Spiritual Guide and Healing Energy Expert',
    imageUrl: 'https://picsum.photos/id/5/200/300',
    ratings: 4.4,
    mailRate: 4.8,
    chatRate: 1.15,
    onlineStatus: 'busy',
  },
  {
    name: 'Chloe Davis',
    description: "Intuitive Counselor for Life's Crossroads",
    imageUrl: 'https://picsum.photos/id/6/200/300',
    ratings: 4.7,
    mailRate: 4.92,
    chatRate: 1.02,
    onlineStatus: 'away',
  },
  {
    name: 'Michael Wilson',
    description: 'Mindfulness Mentor and Meditation Maestro',
    imageUrl: 'https://picsum.photos/id/7/200/300',
    ratings: 4.3,
    mailRate: 4.88,
    chatRate: 1.1,
    onlineStatus: 'online',
  },
  {
    name: 'Sophia Anderson',
    description: 'Life Strategist and Positive Vibes Only Advocate',
    imageUrl: 'https://picsum.photos/id/8/200/300',
    ratings: 4.9,
    mailRate: 4.94,
    chatRate: 0.92,
    onlineStatus: 'offline',
  },
  {
    name: 'William Taylor',
    description: 'Tarot Card Reader and Destiny Decipherer',
    imageUrl: 'https://picsum.photos/id/9/200/300',
    ratings: 4.1,
    mailRate: 4.82,
    chatRate: 1.2,
    onlineStatus: 'online',
  },
  {
    name: 'Mia Jackson',
    description: 'Happiness Alchemist and Love Alleviator',
    imageUrl: 'https://picsum.photos/id/10/200/300',
    ratings: 4.5,
    mailRate: 4.96,
    chatRate: 0.88,
    onlineStatus: 'online',
  },
];
